### ISSUE TITLE
Help on setting up capsule-proxy on AKS w/ Traefik as ingress

### ISSUE THREAD

**Issue by RoFz** [clastix/capsule-proxy#230]
Hello,
I have Capsule set up on an AKS cluster and it works fine. I was just now trying without success to make capsule-proxy work in a very basic scenario (described below) while being behind a Traefik ingress controller.

I guess the issue is my lack of understanding on how kubectl will then interface with capsule-proxy (via traefik). From the documentation it appears that either:

1. capsule-proxy will intercept (the word used in the [docs](https://github.com/clastix/coaks-baseline-architecture/blob/master/guides/capsule-installation.md#installing-capsule-proxy-helm-chart)) all API requests after it is deployed and nothing else needs to be done
2. OR that the user should run a kubectl config set-cluster --server:'https://<capsule_proxy_ingress_fqdn' to alter its config file. 

Which one is the correct alternative?

This is the scenario:

Traefik (answers on 443) -> IngressRoute (inside capsule's namespace) -> capsule-proxy (ClusterIP, port 9001, inside capsule's namespace)

I've tried with capsule-proxy deployed both with enableSSL: true and false. But either way, I'm not sure if kubectl's config must be changed or not (and how).

Update 1:
kubectl --insecure-skip-tls-verify gives me this:

> error: converting (v1.Status) to (v1.APIVersions): unknown conversion

and capsule-proxy logs this:

> {"level":"Level(-4)","ts":"2022-08-30T15:30:42.067Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/08/30 15:30:42 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
> 2022/08/30 15:30:42 cannot retrieve user and group: missing users claim in JWT

**Comment by RoFz** [comment]
Hi. sorry for asking, is this project still alive?

**Comment by prometherion** [comment]
Hi @RoFz and thanks for the question first on its kind regarding Capsule and Traefik!

I'll try to explain step by step how Capsule Proxy is expected to work, especially when dealing with Ingress Controllers.

First, keep in mind that Kubernetes authentication is based on two (sic) strategies: certificates, and tokens. Given the fact we're deploying `capsule-proxy` exposed through an Ingress Controller, when dealing with Certificates, we got the prerequisite of the TLS/SSL, since the authentication is backed by the client certificates (the same thing you would do with `curl --key /path/to/client.key --cert /path/to/client.pem`). In this scenario, the TLS/SSL termination cannot be done at the Ingress Controller level, because otherwise the certificate would be removed from the reverse proxy in the middle: in fact, for this scenario, we strongly suggest using a TLS/SSL passthrough in order to let the `capsule-proxy` to decode the certificate that, otherwise, would be lost by the ingress controller.

After the TLS client certificate validation, the request is proxied by `capsule-proxy` using the authentication data retrieved from it to the Kubernetes API Server, using the impersonation feature offered by the API Server, and here ends the duty of `capsule-proxy`, since it's just decorating the HTTP request with the additional data to mock a native multi-tenancy.

With that said, trying to keep it short: `capsule-proxy` must be used as the Tenant Owners `kubectl` endpoint. Looking for the Traefik documentation (and considering I'm not keen on this popular Ingress Controller) it seems you have to use an `IngressRouteTCP` resource, as suggested [here](https://traefik.io/blog/https-on-kubernetes-using-traefik-proxy/), with the value of `spec.tls.passthrough` key set to `true`.

Let me know if this helps you or not!

**Comment by RoFz** [comment]
Hi @prometherion, thank you very much for the reply.
I have configured a passthrough IngressRouteTCP for capsule-proxy service (ClusterIP, port 9001). I have also executed the kubectl below to change my cluster's API entrypoint:

`k config set-cluster aks-002 --server=https://aks-002.<valid_domain>.com`

kubectl gives me this, then:

> Unable to connect to the server: x509: certificate is valid for capsule-proxy.ops-capsule-001.svc, capsule-proxy, not aks-002.<valid_domain>.com

It looks like the route is working fine as I can see the capsule-proxy logs showing the connection attempts landing there.

> 2022/09/07 22:02:31 http: TLS handshake error from <lb_frontend_ip>:41768: remote error: tls: bad certificate
> 2022/09/07 22:02:31 http: TLS handshake error from <lb_frontend_ip>:41770: remote error: tls: bad certificate
> 2022/09/07 22:02:31 http: TLS handshake error from <lb_frontend_ip>:41772: remote error: tls: bad certificate
> 2022/09/07 22:02:31 http: TLS handshake error from <lb_frontend_ip>:41774: remote error: tls: bad certificate
> 2022/09/07 22:02:31 http: TLS handshake error from <lb_frontend_ip>:41776: remote error: tls: bad certificate

The error above is somewhat expected, since my capsule deployment was deployed with _generateCertificates: true_. kubectl wants a valid/trusted certificate.

So, my next attempt with kubectl was with the infamous _--insecure-skip-tls-verify_ parameter. Now capsule-proxy logs show this:

> {"level":"Level(-4)","ts":"2022-09-07T22:02:08.284Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/09/07 22:02:08 cannot retrieve user and group: missing users claim in JWT
> {"level":"Level(-4)","ts":"2022-09-07T22:02:08.294Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/09/07 22:02:08 cannot retrieve user and group: missing users claim in JWT
> {"level":"Level(-4)","ts":"2022-09-07T22:02:08.303Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/09/07 22:02:08 cannot retrieve user and group: missing users claim in JWT
> {"level":"Level(-4)","ts":"2022-09-07T22:02:08.311Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/09/07 22:02:08 cannot retrieve user and group: missing users claim in JWT
> {"level":"Level(-4)","ts":"2022-09-07T22:02:08.319Z","logger":"proxy","msg":"allowed url path.","url path":"/api"}
> 2022/09/07 22:02:08 cannot retrieve user and group: missing users claim in JWT

And kubectl throws this:

> error: converting (v1.Status) to (v1.APIVersions): unknown conversion

This is my very simple IngressRouteTCP:

> apiVersion: traefik.containo.us/v1alpha1
> kind: IngressRouteTCP
> metadata:
>   name: capsule-proxy-ingress-routes
>   namespace: ops-capsule-001
> spec:
>   entryPoints:
>     - websecure
>   routes:
>     - match: HostSNI(`aks-002.<valid_domain>.com`)
>       services:
>         - name: capsule-proxy
>           namespace: ops-capsule-001
>           port: 9001
>   tls:
>     passthrough: true

Not sure what to try next, maybe reinstall capsule-proxy with a valid Let's Encrypt certificate. I'm under the impression that there's something still missing (or wrong) with my .kube/config.

Any ideas?

Cheers,
Rodrigo

**Comment by prometherion** [comment]
> The error above is somewhat expected, since my capsule deployment was made with generateCertificates: true. kubectl wants a valid/trusted certificate.

Yeah, keep in mind we strongly suggest using Let's Encrypt or custom certificates since we cannot know in advance which host will be used to interact with the Capsule Proxy, along with the well known CA for the common name validation

Regarding the other errors, it seems you're not using a `kubeconfig` by certificates, or with the login strategy offered by the cloud provider (AKS, in this case).

May I ask you to share the `kubeconfig` content? Please, redact sensitive content! 👀

**Comment by prometherion** [comment]
My lack of knowledge, how does the authentication work on AKS?

Are they using a token, or a JWT one?

**Comment by RoFz** [comment]
Hi @prometherion ,

This cluster is integrated with Azure Active Directory and all local accounts have been disabled, even RBAC roles rely on AAD.

I'm not an expert on the topic, but here it goes what I've got while researching:

[auth flow](https://docs.microsoft.com/en-us/azure/aks/media/concepts-identity/auth-flow.png)

According to Microsoft (as explained [here](https://docs.microsoft.com/en-us/azure/aks/concepts-identity#azure-ad-integration)), AKS + AAD works on OIDC, where the cluster API receives a JWT from the client and this gets forwarded to AAD, via an Auth WebHook, to validate/authenticate the token/user.

kubectl relies on exec'ing kubelogin, which holds the JWT token obtained by converting az login's own auth token.

Note: I've initially tried to follow your CoAKS guide [here](https://github.com/clastix/coaks-baseline-architecture/blob/master/guides/capsule-installation.md#installing-capsule-proxy-helm-chart), but ended up having to switch the oidcUsernameClaim helm chart value from unique_name to preferred_username, which seems to be the current AKS standard for v2 tokens, as stated [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set).

Could this be an incompatibility between capsule-proxy and AKS set up with AAD? Capsule works absolutely fine with AAD groups and the Tenant CRD.

**Comment by prometherion** [comment]
I think we have to detect which is the right OIDC username claim, I need to debug it on a AKS cluster.

**Comment by RoFz** [comment]
Hello @prometherion,

sorry for asking, but since we were testing capsule as our multi-tenancy tool of choice this topic has become somewhat critical, did you have the opportunity to debug the issue?

Also, should this issue's label be changed from question to something else?

Rodrigo

**Comment by prometherion** [comment]
@RoFz thanks for the ping!

May I ask you to get in touch privately with me, even on Twitter, LinkedIn, or [Kubernetes Slack workspace, channel #capsule](https://kubernetes.slack.com/archives/C03GETTJQRL)?

**Comment by RoFz** [comment]
@prometherion thanks. Done. LinkedIn.

**Comment by RoFz** [comment]
Hi @prometherion ,

thank you very much for the assistance.

It looks that: capsule-proxy was indeed working, with regular human user accounts, but not with service principals.The decoded kubelogin jwts from both showed that the service principal is missing the necessary oidc claim (unique_name).

I have created another [issue ](#232 )as we would like to understand whether this could be a misconfiguration on the service principal claims specs on our side or could it be that capsule-proxy does not support them at all with Azure AD.

Cheers
